# apiVersion: v1
# kind: Pod
# metadata:
#   name: myhealthcheck
#   labels:
#     name: myhealthcheck
# spec:
#   containers:
#   - name: myhealthcheck-container
#     image: arunvariyath/my_healthcheck:0.0.2
#     command: ["/bin/bash", "-c"]
#     args:
#       - sleep 300;
#     resources:
#       limits:
#         memory: "128Mi"
#         cpu: "500m"

# ---

apiVersion: v1
kind: Pod
metadata:
  name: myhealthcheck
spec:
  containers:
    - name: myhealthcheck-container
      image: arunvariyath/my_healthcheck:0.0.25
      command: ["/bin/bash", "-c"]
      args:
        - |
          mkdir -p /var/log/paj_logs
          python startup_script.py --text "LOVE YOU"
          python healthcheck_script.py --pod-name frontend-798b796d67-79w7c
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
  serviceAccountName: default